name: Update README with File Links by Commit Date

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate list of markdown and PDF files by commit date
      run: |
        echo "Generating file links for README.md by commit date"

        # Create a temp file for the output
        echo "# Blog Contents" > links.md

        # Get the commit history with the date and affected files (Markdown and PDF only, excluding README.md)
        git log --name-only --pretty=format:"## %ad" --date=short | grep -v 'README.md' > commit_history.txt

        # Extract the files and format them as links under each commit date
        CURRENT_DATE=""
        DECLARED_FILES=()
        while IFS= read -r line
        do
          if [[ "$line" =~ ^##\ [0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
            # If the line is a date, set it as the current date heading
            CURRENT_DATE="$line"
            echo "$CURRENT_DATE" >> links.md
          elif [[ "$line" =~ \.md$ || "$line" =~ \.pdf$ ]]; then
            # Only add the file link if it hasn't been declared yet
            if [[ ! " ${DECLARED_FILES[@]} " =~ " ${line} " ]]; then
              DECLARED_FILES+=("$line")
              echo "- [$(basename "$line")]($line)" >> links.md
            fi
          fi
        done < commit_history.txt

    - name: Update README.md
      run: |
        # Inject the generated file links into the README.md file
        awk '/<!-- START LIST -->/{flag=1;next}/<!-- END LIST -->/{flag=0}flag' README.md > temp_readme.md
        cat links.md >> temp_readme.md
        awk '/<!-- END LIST -->/{flag=1;next}flag' README.md >> temp_readme.md

        # Replace the README.md file with the updated one
        mv temp_readme.md README.md

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update README.md with file links by commit date"
        git push
        
