name: Update README with File Links by Commit Date

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate list of markdown and PDF files by commit date
      run: |
        echo "Generating file links for README.md by commit date"

        # Create a temp file for the output
        echo "# Blog Contents" > links.md

        # Get the commit history with the date and affected files (Markdown and PDF only)
        git log --name-only --pretty=format:"## %ad" --date=short > commit_history.txt

        # Extract the files and format them as links under each commit date
        CURRENT_DATE=""
        DECLARED_FILES=""
        while IFS= read -r line
        do
          if [[ "$line" =~ ^##\ [0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
            # If the line is a date, set it as the current date heading
            if [[ "$CURRENT_DATE" != "$line" ]]; then
              CURRENT_DATE="$line"
              echo "$CURRENT_DATE" >> links.md
              DECLARED_FILES=""  # Reset for each date
            fi
          elif [[ "$line" =~ \.md$ || "$line" =~ \.pdf$ ]]; then
            # Ignore README.md as a link
            if [[ "$(basename "$line")" != "README.md" ]]; then
              FILE_NAME=$(basename "$line")
              TITLE="${FILE_NAME%.*}"  # Remove file extension
              # Add only if the file has not been added for this date
              if [[ ! "$DECLARED_FILES" =~ "$FILE_NAME" ]]; then
                echo "- [$TITLE]($line)" >> links.md
                DECLARED_FILES="$DECLARED_FILES $FILE_NAME"
              fi
            fi
          fi
        done < commit_history.txt

    - name: Update README.md
      run: |
        # Extract everything before and after the START/END markers from README.md
        awk 'BEGIN{flag=1} /<!-- START LIST -->/{print;flag=0} /<!-- END LIST -->/{flag=1;print} flag' README.md > temp_readme.md

        # Insert the generated file links between the markers
        awk '/<!-- START LIST -->/{print;system("cat links.md")}/<!-- END LIST -->/{print}' README.md > updated_readme.md

        # Replace the README.md file with the updated one
        mv updated_readme.md README.md

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update README.md with file links by commit date"
        git push
